// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elnzycwsjcgzbllzbvjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbnp5Y3dzamNnemJsbHpidmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTQ3MDMsImV4cCI6MjA2MjU3MDcwM30.s9Olypn5PVob7q9cK1PG_PJJ0LDFGEtCAuZktSsc5uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);